name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:  
  test_build:
    name: test pc-one(full system)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt install -y  make gcc-riscv64-unknown-elf iverilog python3 python3-pip

      - name: Install nox
        run: pip install nox

      - name: Test pc-one
        run: nox -s test_pc_one

  # unit_tests:
  #   name: hardware Unit tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install system dependencies
  #       run: |
  #         sudo apt install -y  make iverilog python3 python3-pip

  #     - name: Install nox
  #       run: pip install nox

  #     - name: Test UART
  #       run: nox -s test_uart
        

